name: Rust Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: jonasgoetz01/codespaces-core:latest
        ports:
          - 8080:8080
        options: --entrypoint "sleep 600"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v2
        with:
          toolchain: stable

      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test
