name: Run Cargo tests on release

on:
  push:
    branches:
      - '*'

runs-on: self-hosted

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build and test
      run: |
          cargo test
