name: Run Cargo tests on release

on:
  push:
    branches:
      - '*'

jobs:
  docker-job:
    runs-on: self-hosted
    services:
      my-docker-service:
        image: jonasgoetz01/codespaces-core:latest
        options: --user root

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: 42core-team/core
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and test
      run: |
          echo "CARGO_HOME: $CARGO_HOME"
          echo "PATH: $PATH"
          /root/.cargo/bin/cargo test
