name: Run Cargo tests on release

on:
  push:
    branches:
      - '*'

jobs:
  docker-job:
    runs-on: self-hosted
    container:
      image: jonasgoetz01/codespaces-core:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and test
      run: |
          cargo test
