name: Rust Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    services:
      docker:
        image: jonasgoetz01/core-runner:latest
        ports:
          - 8080:8080

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test
