name: Rust Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    services:
      docker:
        image: jonasgoetz01/core-runner:latest
        ports:
          - 8080:8080

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          $PATH="/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/bin/remote-cli:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          cargo build --verbose
          cargo test
