name: Run Cargo tests on release

on:
  push:
    branches:
      - '*'

jobs:
  docker-job:
    runs-on: self-hosted
    services:
      my-docker-service:
        image: jonasgoetz01/codespaces-core:latest

    steps:
    - name: Build and test
      run: |
          cargo test
